import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const neueMontreal = localFont({
  variable: "--font-neue-montreal",
  src: [
    {
      path: '../public/fonts/ppneuemontreal-bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/ppneuemontreal-book.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/ppneuemontreal-medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/ppneuemontreal-thin.otf',
      weight: '300',
      style: 'normal',
    },
  ],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${neueMontreal.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
